### ISSUE TITLE
(2) Kafka broker shuts down unexpectedly [2]

### ISSUE THREAD

**Issue by johnantonn** [AuthEceSoftEng/cenote#60]
In the current installation of **cenote dev environment** on my personal laptop (**Linux Subsystem for Windows**), along with the required SW packages:

- mongo
- cockroach
- kafka/zookeeper
- storm
- redis

the **kafka/zookeeper** instance keeps **malfunctioning** and **failing** to write the data to cockroach db.

More specifically, while **cenote-api successfully forwards a POST request from POSTMAN** to write an event, **this event is never actually written in cockroach db**. This happens way too often, especially when changing the WriteTopology in Storm, resulting in difficulties to test and debug new features. Sometimes the issue is resolved temporarily by deleting all kafka/zookeeper logs and restarting all services, however the issue reappears again shortly.

### Indicative screenshots

![post-events](https://user-images.githubusercontent.com/8168416/78884721-12dccd00-7a64-11ea-959d-40b1762abae8.png)
![cenote-api](https://user-images.githubusercontent.com/8168416/78884795-2f790500-7a64-11ea-8090-8f0932e57bf8.png)
![cenote-ui](https://user-images.githubusercontent.com/8168416/78884715-11aba000-7a64-11ea-88ae-fb571af3b7c0.png)

### Kafka/zookeeper log output

[kafka.txt](https://github.com/AuthEceSoftEng/cenote/files/4455631/kafka.txt)
[zookeeper.txt](https://github.com/AuthEceSoftEng/cenote/files/4455633/zookeeper.txt)

### Kafka/zookeeper processes

[kafka-zookeeper-processes.txt](https://github.com/AuthEceSoftEng/cenote/files/4455584/kafka-zookeeper-processes.txt)

### Kafka/zookeeper configuration

![zookeeper-config](https://user-images.githubusercontent.com/8168416/78885365-20df1d80-7a65-11ea-9e36-3c00e02148a6.png)
![kafka-server-config](https://user-images.githubusercontent.com/8168416/78885368-22104a80-7a65-11ea-9cf3-859195101ef9.png)

This issue needs to be fixed permanently in order to safely proceed with features implementation and testing in cenote.

**Comment by johnantonn** [comment]
After successfully managing to modify the `CockroachHandler.py` script with the addition of a new Lua script, the new topology was loaded to Storm and it was tested in a running environment with all the services up 'n' running and cenote-api also running. For the first POST event request, the results were the expected:

- The event was successfully written to cockroach.
- The desired averages were calculated and stored in redis.
- Kafka and Zookeeper did their part.

However, shortly afterwards, the kafka broker failed and went down, and the following messagess appeared in the logs and a new POST event request fails with the message:

```
{
    "message": "Request timed out after 30000ms"
}
```

### cenote-api

```
NestedError: refreshBrokerMetadata failed
[0]     at /home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:378:35
[0]     at /home/giannis/cenote-api/node_modules/async/dist/async.js:473:16
[0]     at next (/home/giannis/cenote-api/node_modules/async/dist/async.js:5329:29)
[0]     at /home/giannis/cenote-api/node_modules/async/dist/async.js:969:16
[0]     at KafkaClient.getAvailableBroker (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:330:12)
[0]     at /home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:373:23
[0]     at nextTask (/home/giannis/cenote-api/node_modules/async/dist/async.js:5324:14)
[0]     at Object.waterfall (/home/giannis/cenote-api/node_modules/async/dist/async.js:5334:5)
[0]     at KafkaClient.refreshBrokerMetadata (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:372:9)
[0]     at Immediate._onImmediate (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:782:20)
[0]     at processImmediate (internal/timers.js:456:21)
[0] Caused By: Error: Unable to find available brokers to try
[0]     at KafkaClient.getAvailableBroker (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:330:21)
[0]     at /home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:373:23
[0]     at nextTask (/home/giannis/cenote-api/node_modules/async/dist/async.js:5324:14)
[0]     at Object.waterfall (/home/giannis/cenote-api/node_modules/async/dist/async.js:5334:5)
[0]     at KafkaClient.refreshBrokerMetadata (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:372:9)
[0]     at Immediate._onImmediate (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:782:20)
[0]     at processImmediate (internal/timers.js:456:21) {
[0]   nested: Error: Unable to find available brokers to try
[0]       at KafkaClient.getAvailableBroker (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:330:21)
[0]       at /home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:373:23
[0]       at nextTask (/home/giannis/cenote-api/node_modules/async/dist/async.js:5324:14)
[0]       at Object.waterfall (/home/giannis/cenote-api/node_modules/async/dist/async.js:5334:5)
[0]       at KafkaClient.refreshBrokerMetadata (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:372:9)
[0]       at Immediate._onImmediate (/home/giannis/cenote-api/node_modules/kafka-node/lib/kafkaClient.js:782:20)
[0]       at processImmediate (internal/timers.js:456:21)
[0] 
}
```

### Kafka log

```
ERROR Failed to clean up log for __consumer_offsets-11 in dir /tmp/kafka-logs due to IOException (kafka.server.LogDirFailureChannel)
java.io.IOException: Invalid argument
	at java.io.RandomAccessFile.setLength(Native Method)
	at kafka.log.AbstractIndex.$anonfun$resize$1(AbstractIndex.scala:188)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.log.AbstractIndex.resize(AbstractIndex.scala:174)
	at kafka.log.AbstractIndex.$anonfun$trimToValidSize$1(AbstractIndex.scala:240)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
	at kafka.log.AbstractIndex.trimToValidSize(AbstractIndex.scala:240)
	at kafka.log.LogSegment.onBecomeInactiveSegment(LogSegment.scala:508)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:595)
	at kafka.log.Cleaner.$anonfun$doClean$6(LogCleaner.scala:530)
	at kafka.log.Cleaner.$anonfun$doClean$6$adapted(LogCleaner.scala:529)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at kafka.log.Cleaner.doClean(LogCleaner.scala:529)
	at kafka.log.Cleaner.clean(LogCleaner.scala:503)
	at kafka.log.LogCleaner$CleanerThread.cleanLog(LogCleaner.scala:372)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:345)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:325)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:314)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
[2020-04-10 12:18:31,042] INFO [ReplicaManager broker=0] Stopping serving replicas in dir /tmp/kafka-logs (kafka.server.ReplicaManager)
[2020-04-10 12:18:31,052] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-37, Hello-Kafka-0, __consumer_offsets-38, cenoteIncoming-0, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, test-0, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaFetcherManager)
[2020-04-10 12:18:31,058] INFO [ReplicaAlterLogDirsManager on broker 0] Removed fetcher for partitions HashSet(__consumer_offsets-22, __consumer_offsets-30, __consumer_offsets-25, __consumer_offsets-35, __consumer_offsets-37, Hello-Kafka-0, __consumer_offsets-38, cenoteIncoming-0, __consumer_offsets-13, __consumer_offsets-8, __consumer_offsets-21, __consumer_offsets-4, __consumer_offsets-27, __consumer_offsets-7, __consumer_offsets-9, __consumer_offsets-46, __consumer_offsets-41, __consumer_offsets-33, __consumer_offsets-23, __consumer_offsets-49, __consumer_offsets-47, __consumer_offsets-16, test-0, __consumer_offsets-28, __consumer_offsets-31, __consumer_offsets-36, __consumer_offsets-42, __consumer_offsets-3, __consumer_offsets-18, __consumer_offsets-15, __consumer_offsets-24, __consumer_offsets-17, __consumer_offsets-48, __consumer_offsets-19, __consumer_offsets-11, __consumer_offsets-2, __consumer_offsets-43, __consumer_offsets-6, __consumer_offsets-14, __consumer_offsets-20, __consumer_offsets-0, __consumer_offsets-44, __consumer_offsets-39, __consumer_offsets-12, __consumer_offsets-45, __consumer_offsets-1, __consumer_offsets-5, __consumer_offsets-26, __consumer_offsets-29, __consumer_offsets-34, __consumer_offsets-10, __consumer_offsets-32, __consumer_offsets-40) (kafka.server.ReplicaAlterLogDirsManager)
```

### Zookeeper

```
[2020-04-10 12:18:31,579] WARN Unable to read additional data from client sessionid 0x100000072bc0000, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn)
```

### Full logs

[kafka.zip](https://github.com/AuthEceSoftEng/cenote/files/4460908/kafka.zip)
[zookeeper.zip](https://github.com/AuthEceSoftEng/cenote/files/4460909/zookeeper.zip)

**Comment by johnantonn** [comment]
After searching various sites for solutions and not finding one, I raised the issue to stackoverflow:

https://stackoverflow.com/questions/61138588/kafka-broker-shuts-down-unexpectedly

Until an acceptable solution/reply is offered, I experimentally reduced the config value:

`offsets.topic.num.partitions = 50` 

as below:

`offsets.topic.num.partitions = 1`

and so far kafka broker hasn't crushed. 


Closing the issue for now and will re-open if necessary.
